/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.management.system;

import java.awt.Toolkit;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariwa
 */
public class ResetPassword extends javax.swing.JFrame {
Connection con = null;
ResultSet rs = null;
PreparedStatement pst = null;
public String user;
public Icon icon = new javax.swing.ImageIcon(getClass().getResource("kwanza tukule icon.png"));
    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
        ImageIcon img = new ImageIcon("kwanza tukule icon.png");
        this.setIconImage(img.getImage());
    }
    public ResetPassword(String username)
    {
        this.user = username;
        initComponents();
        setIcon();
        ImageIcon img = new ImageIcon("kwanza tukule icon.png");
        this.setIconImage(img.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        newPasswordText = new javax.swing.JPasswordField();
        confirmPasswordText = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setPreferredSize(new java.awt.Dimension(737, 470));
        setTitle("Kwanza Tukule | Reset Password");
        getContentPane().setLayout(null);

        resetLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        resetLabel.setText("Reset Password");
        getContentPane().add(resetLabel);
        resetLabel.setBounds(282, 65, 197, 30);

        newPasswordLabel.setText("New Password:");
        getContentPane().add(newPasswordLabel);
        newPasswordLabel.setBounds(89, 162, 94, 16);

        confirmPasswordLabel.setText("Confirm Password:");
        getContentPane().add(confirmPasswordLabel);
        confirmPasswordLabel.setBounds(89, 265, 118, 16);

        resetButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(333, 367, 116, 39);

        newPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordTextActionPerformed(evt);
            }
        });
        getContentPane().add(newPasswordText);
        newPasswordText.setBounds(189, 157, 450, 26);

        confirmPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordTextActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPasswordText);
        confirmPasswordText.setBounds(213, 260, 426, 26);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/kwanza tukule black.png"))); // NOI18N
        logoLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        if(newPasswordText.getText().equals(confirmPasswordText.getText()))
        {
            try{
                String updateQuery = "UPDATE users SET password=? WHERE email=?";
                con = DriverManager.getConnection("jdbc:mysql://194.5.156.94:3306/u843360242_tukule?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","u843360242_tukule","cocaine");
                pst = con.prepareStatement(updateQuery);
                pst.setString(1, md5(confirmPasswordText.getPassword()));
                pst.setString(2, user);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your Password Reset is complete.","Complete",JOptionPane.INFORMATION_MESSAGE,icon);
                Login lg = new Login();
                this.setVisible(false);
                lg.setVisible(true);
            }catch( Exception ex){
                JOptionPane.showMessageDialog(null,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Passwords do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void newPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordTextActionPerformed
        if(newPasswordText.getText().equals(confirmPasswordText.getText()))
        {
            try{
                String updateQuery = "UPDATE users SET password=? WHERE email=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Kwanza Tukule?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","samokoth.1999");
                pst = con.prepareStatement(updateQuery);
                pst.setString(1, md5(confirmPasswordText.getPassword()));
                pst.setString(2, user);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your Password Reset is complete.","Complete",JOptionPane.INFORMATION_MESSAGE,icon);
                Login lg = new Login();
                this.setVisible(false);
                lg.setVisible(true);
            }catch( Exception ex){
                JOptionPane.showMessageDialog(null,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Passwords do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_newPasswordTextActionPerformed

    private void confirmPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordTextActionPerformed
        if(newPasswordText.getText().equals(confirmPasswordText.getText()))
        {
            try{
                String updateQuery = "UPDATE users SET password=? WHERE email=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Kwanza Tukule?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","samokoth.1999");
                pst = con.prepareStatement(updateQuery);
                pst.setString(1, confirmPasswordText.getText());
                pst.setString(2, user);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your Password Reset is complete.","Complete",JOptionPane.INFORMATION_MESSAGE,icon);
                Login lg = new Login();
                this.setVisible(false);
                lg.setVisible(true);
            }catch( Exception ex){
                JOptionPane.showMessageDialog(null,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Passwords do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_confirmPasswordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField confirmPasswordText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel resetLabel;
    // End of variables declaration//GEN-END:variables
private String md5 (char[] c){
        try{
            MessageDigest digest = MessageDigest.getInstance("MD5");
            digest.update((new String (c)).getBytes("UTF8"));
            String str = new String(digest.digest());
            return str;
        }catch(Exception ex){
            return "";
        }
    }
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kwanza tukule icon.png")));
    }
}
