/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.management.system;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Mariwa
 */
public class Dashboard extends javax.swing.JFrame {
Connection con = null;
ResultSet rs = null;
PreparedStatement pst = null;
public String user;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        sideBar.setSize(0,0);
        menuClose.setSize(0,0);
        customersPanel.setSize(0,0);
        summaryPanel.setSize(0,0);
        ordersPanel.setSize(0,0);
        stockPanel.setSize(0,0);
    }

    public Dashboard(String username) {
         this.user=username;
         initComponents();
         
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        nullPanel = new javax.swing.JPanel();
        menuOpen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        customerSideBar = new javax.swing.JLabel();
        menuClose = new javax.swing.JLabel();
        stockSideBar = new javax.swing.JLabel();
        orderSideBar = new javax.swing.JLabel();
        summarySideBar = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        customersPanel = new javax.swing.JPanel();
        customersPageTitle = new javax.swing.JLabel();
        stockPanel = new javax.swing.JPanel();
        stockPageTitle = new javax.swing.JLabel();
        ordersPanel = new javax.swing.JPanel();
        ordersPageTitle = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        summaryPageTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kwanza Tukule | Dashboard");

        setPreferredSize(new java.awt.Dimension(1650, 1080));
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/Kwanza Tukule.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 190, 78);
        jPanel1.add(userLabel);
        userLabel.setBounds(1688, 39, 0, 0);

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        usernameLabel.setText(user);
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(1000, 20, 200, 20);

        nullPanel.setLayout(null);
        jPanel1.add(nullPanel);
        nullPanel.setBounds(210, 60, 1190, 730);

        menuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/menu.png"))); // NOI18N
        menuOpen.setText("jLabel2");
        menuOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuOpenMousePressed(evt);
            }
        });
        jPanel1.add(menuOpen);
        menuOpen.setBounds(10, 90, 190, 60);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 60, 22);

        sideBar.setBackground(new java.awt.Color(0, 255, 102));
        sideBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sideBar.setForeground(new java.awt.Color(255, 255, 255));

        customerSideBar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        customerSideBar.setText("Customers");
        customerSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerSideBarMousePressed(evt);
            }
        });

        menuClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/menuClose.png"))); // NOI18N
        menuClose.setText("jLabel3");
        menuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCloseMousePressed(evt);
            }
        });

        stockSideBar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        stockSideBar.setText("Stock");
        stockSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockSideBarMousePressed(evt);
            }
        });

        orderSideBar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        orderSideBar.setText("Orders");
        orderSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderSideBarMousePressed(evt);
            }
        });

        summarySideBar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        summarySideBar.setText("Summary");
        summarySideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                summarySideBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuClose, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summarySideBar)
                            .addComponent(orderSideBar)
                            .addComponent(stockSideBar)
                            .addComponent(customerSideBar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(menuClose, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(customerSideBar)
                .addGap(40, 40, 40)
                .addComponent(stockSideBar)
                .addGap(41, 41, 41)
                .addComponent(orderSideBar)
                .addGap(48, 48, 48)
                .addComponent(summarySideBar)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jPanel1.add(sideBar);
        sideBar.setBounds(0, 80, 0, 720);

        logoutButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(1130, 20, 106, 29);

        customersPanel.setBounds(new java.awt.Rectangle(210, 60, 1190, 730));

        customersPageTitle.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        customersPageTitle.setText("Customers");

        javax.swing.GroupLayout customersPanelLayout = new javax.swing.GroupLayout(customersPanel);
        customersPanel.setLayout(customersPanelLayout);
        customersPanelLayout.setHorizontalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(customersPageTitle)
                .addContainerGap(1002, Short.MAX_VALUE))
        );
        customersPanelLayout.setVerticalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(customersPageTitle)
                .addContainerGap(656, Short.MAX_VALUE))
        );

        jPanel1.add(customersPanel);
        customersPanel.setBounds(130, 120, 1190, 730);

        stockPanel.setBounds(new java.awt.Rectangle(210, 60, 1190, 730));

        stockPageTitle.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        stockPageTitle.setText("Stock");

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(stockPageTitle)
                .addContainerGap(1089, Short.MAX_VALUE))
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(stockPageTitle)
                .addContainerGap(656, Short.MAX_VALUE))
        );

        jPanel1.add(stockPanel);
        stockPanel.setBounds(130, 230, 1190, 730);

        ordersPanel.setBounds(new java.awt.Rectangle(210, 60, 1190, 730));

        ordersPageTitle.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        ordersPageTitle.setText("Orders");

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ordersPageTitle)
                .addContainerGap(1055, Short.MAX_VALUE))
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ordersPageTitle)
                .addContainerGap(658, Short.MAX_VALUE))
        );

        jPanel1.add(ordersPanel);
        ordersPanel.setBounds(110, 350, 1190, 730);

        summaryPanel.setBounds(new java.awt.Rectangle(210, 60, 1190, 730));

        summaryPageTitle.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        summaryPageTitle.setText("Summary");
        summaryPageTitle.setBounds(new java.awt.Rectangle(-32633, -32382, 45, 16));

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(summaryPageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1013, Short.MAX_VALUE))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(summaryPageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(650, Short.MAX_VALUE))
        );

        jPanel1.add(summaryPanel);
        summaryPanel.setBounds(110, 470, 1190, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpenMousePressed
        Thread th = new Thread(){
            @Override
        public void run(){
           try{
               for(int a=0;a<=5;a++){
                   Thread.sleep(50);
                   if(a==1){
                       sideBar.setBounds(0,80,40,720);
                       menuOpen.setSize(0,0);
                       menuClose.setBounds(20,80,180,80);
                       jLabel2.setSize(0,0);
                   }
                       if(a==2){
                           sideBar.setBounds(0,80,80,720);
                       }
                       if(a==3){
                           sideBar.setBounds(0,80,120,720);
                       }
                       if(a==4){
                           sideBar.setBounds(0,80,160,720);
                       }
                       if(a==5){
                           sideBar.setBounds(0,80,200,720);
                       }
               }
           }catch(Exception ex){
               System.out.println(ex);
           } 
        }
    };th.start();
    }//GEN-LAST:event_menuOpenMousePressed

    private void menuCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCloseMousePressed
        Thread th = new Thread(){
            @Override
        public void run(){
           try{
               for(int a=0;a<=5;a++){
                   Thread.sleep(50);
                   if(a==1){
                       sideBar.setBounds(0,80,200,720);            
               
                   }
                       if(a==2){
                           sideBar.setBounds(0,80,160,720);
                       }
                       if(a==3){
                           sideBar.setBounds(0,80,120,720);
                       }
                       if(a==4){
                           sideBar.setBounds(0,80,80,720);
                       }
                       if(a==5){
                           sideBar.setBounds(0,80,0,720);
                           menuOpen.setBounds(10,90,190,60);
                           jLabel2.setBounds(40,108,60,30);
                       }
               }
           }catch(Exception ex){
               System.out.println(ex);
           } 
        }
    };th.start();
     nullPanel.setBounds(210,60,1190,730);
     customersPanel.setSize(0,0);
     summaryPanel.setSize(0,0);
     ordersPanel.setSize(0,0);
     stockPanel.setSize(0,0);
    }//GEN-LAST:event_menuCloseMousePressed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
            Login lg = new Login();
            this.setVisible(false);
            lg.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void customerSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSideBarMousePressed
     customersPanel.setBounds(210,60,1190,730);
     summaryPanel.setSize(0,0);
     ordersPanel.setSize(0,0);
     stockPanel.setSize(0,0);
     nullPanel.setSize(0,0);
    }//GEN-LAST:event_customerSideBarMousePressed

    private void stockSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockSideBarMousePressed
      stockPanel.setBounds(210,60,1190,730);
      customersPanel.setSize(0,0);
      ordersPanel.setSize(0,0);
      summaryPanel.setSize(0,0);
      nullPanel.setSize(0,0);
    }//GEN-LAST:event_stockSideBarMousePressed

    private void orderSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderSideBarMousePressed
      ordersPanel.setBounds(210,60,1190,730);
      summaryPanel.setSize(0,0);
      customersPanel.setSize(0,0);
      stockPanel.setSize(0,0);
      nullPanel.setSize(0,0);
    }//GEN-LAST:event_orderSideBarMousePressed

    private void summarySideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_summarySideBarMousePressed
      summaryPanel.setBounds(210,60,1190,730);
      customersPanel.setSize(0,0);
      ordersPanel.setSize(0,0);
      stockPanel.setSize(0,0);
      nullPanel.setSize(0,0);
    }//GEN-LAST:event_summarySideBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerSideBar;
    private javax.swing.JLabel customersPageTitle;
    private javax.swing.JPanel customersPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuClose;
    private javax.swing.JLabel menuOpen;
    private javax.swing.JPanel nullPanel;
    private javax.swing.JLabel orderSideBar;
    private javax.swing.JLabel ordersPageTitle;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel stockPageTitle;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JLabel stockSideBar;
    private javax.swing.JLabel summaryPageTitle;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JLabel summarySideBar;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
