/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.management.system;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Mariwa
 */
public class Dashboard extends javax.swing.JFrame {
Connection con = null;
ResultSet rs = null;
PreparedStatement pst = null;
public String user;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        sideBar.setSize(0,0);
        menuClose.setSize(0,0);
    }

    public Dashboard(String username) {
         this.user=username;
         initComponents();
         
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuOpen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        task1 = new javax.swing.JLabel();
        menuClose = new javax.swing.JLabel();
        task2 = new javax.swing.JLabel();
        task3 = new javax.swing.JLabel();
        task4 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kwanza Tukule | Dashboard");

        setPreferredSize(new java.awt.Dimension(1650, 1080));
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/Kwanza Tukule.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 190, 78);
        jPanel1.add(userLabel);
        userLabel.setBounds(1688, 39, 0, 0);

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        usernameLabel.setText(user);
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(1000, 20, 200, 20);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 60, 1190, 730);

        menuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/menu.png"))); // NOI18N
        menuOpen.setText("jLabel2");
        menuOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuOpenMousePressed(evt);
            }
        });
        jPanel1.add(menuOpen);
        menuOpen.setBounds(10, 90, 190, 60);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 60, 22);

        sideBar.setBackground(new java.awt.Color(0, 255, 102));
        sideBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sideBar.setForeground(new java.awt.Color(255, 255, 255));

        task1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        task1.setText("Task");
        task1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                task1MousePressed(evt);
            }
        });

        menuClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/menuClose.png"))); // NOI18N
        menuClose.setText("jLabel3");
        menuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCloseMousePressed(evt);
            }
        });

        task2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        task2.setText("Task");
        task2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                task2MousePressed(evt);
            }
        });

        task3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        task3.setText("Task");
        task3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                task3MousePressed(evt);
            }
        });

        task4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        task4.setText("Task");
        task4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                task4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuClose, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task4)
                            .addComponent(task3)
                            .addComponent(task2)
                            .addComponent(task1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(menuClose, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(task1)
                .addGap(40, 40, 40)
                .addComponent(task2)
                .addGap(41, 41, 41)
                .addComponent(task3)
                .addGap(48, 48, 48)
                .addComponent(task4)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jPanel1.add(sideBar);
        sideBar.setBounds(0, 80, 0, 720);

        logoutButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(1130, 20, 106, 29);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/avatar.png"))); // NOI18N
        userIcon.setText("jLabel4");
        jPanel1.add(userIcon);
        userIcon.setBounds(940, 10, 70, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpenMousePressed
        Thread th = new Thread(){
            @Override
        public void run(){
           try{
               for(int a=0;a<=5;a++){
                   Thread.sleep(50);
                   if(a==1){
                       sideBar.setBounds(0,80,40,720);
                       menuOpen.setSize(0,0);
                       menuClose.setBounds(20,80,180,80);
                       jLabel2.setSize(0,0);
                   }
                       if(a==2){
                           sideBar.setBounds(0,80,80,720);
                       }
                       if(a==3){
                           sideBar.setBounds(0,80,120,720);
                       }
                       if(a==4){
                           sideBar.setBounds(0,80,160,720);
                       }
                       if(a==5){
                           sideBar.setBounds(0,80,200,720);
                       }
               }
           }catch(Exception ex){
               System.out.println(ex);
           } 
        }
    };th.start();
    }//GEN-LAST:event_menuOpenMousePressed

    private void menuCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCloseMousePressed
        Thread th = new Thread(){
            @Override
        public void run(){
           try{
               for(int a=0;a<=5;a++){
                   Thread.sleep(50);
                   if(a==1){
                       sideBar.setBounds(0,80,200,720);            
               
                   }
                       if(a==2){
                           sideBar.setBounds(0,80,160,720);
                       }
                       if(a==3){
                           sideBar.setBounds(0,80,120,720);
                       }
                       if(a==4){
                           sideBar.setBounds(0,80,80,720);
                       }
                       if(a==5){
                           sideBar.setBounds(0,80,0,720);
                           menuOpen.setBounds(10,90,190,60);
                           jLabel2.setBounds(40,108,60,30);
                       }
               }
           }catch(Exception ex){
               System.out.println(ex);
           } 
        }
    };th.start();
    }//GEN-LAST:event_menuCloseMousePressed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
            Login lg = new Login();
            this.setVisible(false);
            lg.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void task1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_task1MousePressed

    private void task2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2MousePressed

    private void task3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_task3MousePressed

    private void task4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_task4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuClose;
    private javax.swing.JLabel menuOpen;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel task1;
    private javax.swing.JLabel task2;
    private javax.swing.JLabel task3;
    private javax.swing.JLabel task4;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
