/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.management.system;


import java.awt.Toolkit;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariwa
 */
public class Registration extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public String userName;
    public Icon icon = new javax.swing.ImageIcon(getClass().getResource("kwanza tukule icon.png"));
    
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setIcon();
        ImageIcon img = new ImageIcon("C:\\Users\\samue\\Desktop\\Kwanza Tukule Management System\\src\\kwanza\\tukule\\management\\system\\kwanza tukule icon.png");
        this.setIconImage(img.getImage());
    }
    
    public static boolean email_Validation(String email){
       boolean status = false;
       String email_Pattern = "^[A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
       Pattern pattern = Pattern.compile(email_Pattern);
       Matcher matcher = pattern.matcher(email);
       if(matcher.matches()){
          status = true;
         }
      else{
          status = false;
         }
         return status;
      }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        pNumberLabel = new javax.swing.JLabel();
        eAddressLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        roleText = new javax.swing.JTextField();
        cPasswordLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nationalIdNumberLabel = new javax.swing.JLabel();
        yobLabel = new javax.swing.JLabel();
        staffIdNumberLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        yobText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        loginLink = new javax.swing.JLabel();
        fNameText = new javax.swing.JTextField();
        pNumberText = new javax.swing.JTextField();
        nationalIdNumberText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        cPasswordText = new javax.swing.JPasswordField();
        usernameText = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        staffIdNumberText = new javax.swing.JTextField();
        eAddressText = new javax.swing.JTextField();
        lNameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(737, 570));
        setTitle("Kwanza Tukule | Registration");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        fNameLabel.setText("First Name:");
        getContentPane().add(fNameLabel);
        fNameLabel.setBounds(42, 108, 82, 20);

        lNameLabel.setText("Last Name:");
        getContentPane().add(lNameLabel);
        lNameLabel.setBounds(350, 108, 80, 20);

        pNumberLabel.setText("Phone Number:");
        getContentPane().add(pNumberLabel);
        pNumberLabel.setBounds(42, 156, 112, 20);

        eAddressLabel.setText("E-mail Address:");
        getContentPane().add(eAddressLabel);
        eAddressLabel.setBounds(350, 156, 113, 20);

        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(350, 306, 77, 20);

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(42, 351, 73, 20);

        roleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTextActionPerformed(evt);
            }
        });
        getContentPane().add(roleText);
        roleText.setBounds(79, 293, 233, 26);

        cPasswordLabel.setText("Confirm Password:");
        getContentPane().add(cPasswordLabel);
        cPasswordLabel.setBounds(350, 346, 135, 20);

        roleLabel.setText("Role:");
        getContentPane().add(roleLabel);
        roleLabel.setBounds(42, 298, 37, 20);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel9.setText("REGISTRATION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(266, 50, 197, 50);

        nationalIdNumberLabel.setText("National ID Number:");
        getContentPane().add(nationalIdNumberLabel);
        nationalIdNumberLabel.setBounds(42, 200, 148, 20);

        yobLabel.setText("Year of Birth:");
        getContentPane().add(yobLabel);
        yobLabel.setBounds(42, 246, 95, 20);

        staffIdNumberLabel.setText("Staff ID Number:");
        getContentPane().add(staffIdNumberLabel);
        staffIdNumberLabel.setBounds(350, 200, 122, 20);

        genderLabel.setText("Gender:");
        getContentPane().add(genderLabel);
        genderLabel.setBounds(350, 246, 57, 20);

        yobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yobTextActionPerformed(evt);
            }
        });
        getContentPane().add(yobText);
        yobText.setBounds(140, 241, 177, 26);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/kwanza tukule black.png"))); // NOI18N

        clearButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginLink.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        loginLink.setForeground(new java.awt.Color(51, 153, 255));
        loginLink.setText("Have an account? Login");
        loginLink.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginLinkMouseMoved(evt);
            }
        });
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginLinkMousePressed(evt);
            }
        });

        fNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTextActionPerformed(evt);
            }
        });

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        cPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPasswordTextActionPerformed(evt);
            }
        });

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        eAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAddressTextActionPerformed(evt);
            }
        });

        lNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(loginLink))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nationalIdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(staffIdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalIdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffIdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(loginLink)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 840, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPasswordTextActionPerformed

    private void fNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTextActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
         boolean  status = Registration.email_Validation(eAddressText.getText());
        if(status){        
        if(passwordText.getText().equals(cPasswordText.getText()))
        {
        try{
            String query = "INSERT INTO `users`(`firstname`, `lastname`, `number`, `email`, `nationalID`, `staffID`, `yob`, `gender`, `role`, `username`, `password`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://194.5.156.94:3306/u843360242_tukule?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","u843360242_tukule","cocaine");
            pst = con.prepareStatement(query);
            pst.setString(1,fNameText.getText());
            pst.setString(2,lNameText.getText());
            pst.setString(3,pNumberText.getText());
            pst.setString(4,eAddressText.getText());
            pst.setString(5,nationalIdNumberText.getText());
            pst.setString(6,staffIdNumberText.getText());
            pst.setString(7,yobText.getText());
            pst.setString(8,genderComboBox.getSelectedItem().toString());
            pst.setString(9,roleText.getText());
            pst.setString(10,usernameText.getText());
            pst.setString(11,md5(passwordText.getPassword()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registration Complete.","Complete",JOptionPane.INFORMATION_MESSAGE,icon);
            Login lg = new Login();
            this.setVisible(false);
            lg.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Passwords do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Email Address is not valid.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_registerButtonActionPerformed
        
    private void lNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTextActionPerformed

    private void eAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eAddressTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void roleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTextActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void yobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yobTextActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        fNameText.setText("");
        lNameText.setText("");
        pNumberText.setText("");
        eAddressText.setText("");
        nationalIdNumberText.setText("");
        staffIdNumberText.setText("");
        genderComboBox.setSelectedIndex(0);
        yobText.setText("");
        roleText.setText("");
        usernameText.setText("");
        passwordText.setText("");
        cPasswordText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void loginLinkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_loginLinkMouseMoved

    private void loginLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMousePressed
        Login lg = new Login();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_loginLinkMousePressed

    private String md5 (char[] c){
        try{
            MessageDigest digest = MessageDigest.getInstance("MD5");
            digest.update((new String (c)).getBytes("UTF8"));
            String str = new String(digest.digest());
            return str;
        }catch(Exception ex){
            return "";
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cPasswordLabel;
    private javax.swing.JPasswordField cPasswordText;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel eAddressLabel;
    private javax.swing.JTextField eAddressText;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameText;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField lNameText;
    private javax.swing.JLabel loginLink;
    private javax.swing.JLabel nationalIdNumberLabel;
    private javax.swing.JTextField nationalIdNumberText;
    private javax.swing.JLabel pNumberLabel;
    private javax.swing.JTextField pNumberText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JTextField roleText;
    private javax.swing.JLabel staffIdNumberLabel;
    private javax.swing.JTextField staffIdNumberText;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    private javax.swing.JLabel yobLabel;
    private javax.swing.JTextField yobText;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kwanza tukule icon.png")));
    }
}
