/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.version.pkg1.pkg0;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Mariwa
 */
public class Registration extends javax.swing.JFrame {
    Connection connect = databaseConnection.connection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    public String userName;
    public Icon icon = new javax.swing.ImageIcon(getClass().getResource("kwanza tukule icon.png"));
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setIcon();
        ImageIcon img = new ImageIcon("kwanza tukule icon.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        RegistrationTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        RegistrationIcon = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        RegistrationImage = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        pNumberLabel = new javax.swing.JLabel();
        eAddressLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        fNameText = new javax.swing.JTextField();
        lNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        roleText = new javax.swing.JTextField();
        pNumberText = new javax.swing.JTextField();
        eAddressText = new javax.swing.JTextField();
        cPasswordLabel = new javax.swing.JLabel();
        cPasswordText = new javax.swing.JPasswordField();
        roleLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        nationalIdNumberLabel = new javax.swing.JLabel();
        yobLabel = new javax.swing.JLabel();
        staffIdNumberLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        nationalIdNumberText = new javax.swing.JTextField();
        staffIdNumberText = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        yobText = new javax.swing.JTextField();
        loginLink = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        fNameLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kwanza Tukule | Registration");
        setBackground(new java.awt.Color(255, 255, 255));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrationTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        RegistrationTitle.setText("REGISTRATION");
        backgroundPanel.add(RegistrationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jPanel4.setOpaque(false);

        RegistrationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/version/pkg1/pkg0/kwanza tukule logo.png"))); // NOI18N

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/version/pkg1/pkg0/avatar2.png"))); // NOI18N

        welcomeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(102, 102, 102));
        welcomeLabel.setText("Welcome");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeLabel)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(RegistrationIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(avatar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(RegistrationIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 670));

        RegistrationImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/version/pkg1/pkg0/RegistrationImage.jpg"))); // NOI18N
        backgroundPanel.add(RegistrationImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 670));

        lNameLabel.setText("Last Name:");
        backgroundPanel.add(lNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 80, -1));

        pNumberLabel.setText("Phone Number:");
        backgroundPanel.add(pNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 20));

        eAddressLabel.setText("E-mail Address:");
        backgroundPanel.add(eAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 110, 20));

        usernameLabel.setText("Username:");
        backgroundPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 70, -1));

        passwordLabel.setText("Password:");
        backgroundPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 70, 20));

        fNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(fNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 210, -1));

        lNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(lNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 230, -1));

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 210, -1));

        roleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(roleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 230, -1));
        backgroundPanel.add(pNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 180, -1));

        eAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAddressTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(eAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 200, -1));

        cPasswordLabel.setText("Confirm Password:");
        backgroundPanel.add(cPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 120, 20));

        cPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPasswordTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(cPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 180, -1));

        roleLabel.setText("Role:");
        backgroundPanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 40, -1));

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 230, -1));

        nationalIdNumberLabel.setText("National ID Number:");
        backgroundPanel.add(nationalIdNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 140, -1));

        yobLabel.setText("Year of Birth:");
        backgroundPanel.add(yobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 90, -1));

        staffIdNumberLabel.setText("Staff ID Number:");
        backgroundPanel.add(staffIdNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 120, 20));

        genderLabel.setText("Gender:");
        backgroundPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 60, -1));
        backgroundPanel.add(nationalIdNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, -1));
        backgroundPanel.add(staffIdNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 190, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        backgroundPanel.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 100, -1));

        yobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yobTextActionPerformed(evt);
            }
        });
        backgroundPanel.add(yobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 180, -1));

        loginLink.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        loginLink.setForeground(new java.awt.Color(51, 153, 255));
        loginLink.setText("Have an account? Login");
        loginLink.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginLinkMouseMoved(evt);
            }
        });
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginLinkMousePressed(evt);
            }
        });
        backgroundPanel.add(loginLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        clearButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 130, 41));

        fNameLabel.setText("First Name:");
        backgroundPanel.add(fNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, 20));

        registerButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTextActionPerformed

    private void lNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void roleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTextActionPerformed

    private void eAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eAddressTextActionPerformed

    private void cPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPasswordTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void yobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yobTextActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        fNameText.setText("");
        lNameText.setText("");
        pNumberText.setText("");
        eAddressText.setText("");
        nationalIdNumberText.setText("");
        staffIdNumberText.setText("");
        genderComboBox.setSelectedIndex(0);
        yobText.setText("");
        roleText.setText("");
        usernameText.setText("");
        passwordText.setText("");
        cPasswordText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void loginLinkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_loginLinkMouseMoved

    private void loginLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMousePressed
        Login lg = new Login();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_loginLinkMousePressed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        boolean  status = Registration.email_Validation(eAddressText.getText());
        if(status){
            if(passwordText.getText().equals(cPasswordText.getText()))
            {
                try{
                    String salt = "EqdmPh53c9x33EygXpTpcoJvc4VXLK";
                    String storePass = passwordUtils.generateSecurePassword(new String(passwordText.getPassword()),salt);
                    String query = "INSERT INTO `users`(`firstname`, `lastname`, `number`, `email`, `nationalID`, `staffID`, `yob`, `gender`, `role`, `username`, `password`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                    pst = connect.prepareStatement(query);
                    pst.setString(1,fNameText.getText());
                    pst.setString(2,lNameText.getText());
                    pst.setString(3,pNumberText.getText());
                    pst.setString(4,eAddressText.getText());
                    pst.setString(5,nationalIdNumberText.getText());
                    pst.setString(6,staffIdNumberText.getText());
                    pst.setString(7,yobText.getText());
                    pst.setString(8,genderComboBox.getSelectedItem().toString());
                    pst.setString(9,roleText.getText());
                    pst.setString(10,usernameText.getText());
                    pst.setString(11,storePass);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Registration Complete.","Complete",JOptionPane.INFORMATION_MESSAGE,icon);
                    Login lg = new Login();
                    this.setVisible(false);
                    lg.setVisible(true);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Your Passwords do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Your Email Address is not valid.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_registerButtonActionPerformed
public static boolean email_Validation(String email){
       boolean status = false;
       String email_Pattern = "^[A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
       Pattern pattern = Pattern.compile(email_Pattern);
       Matcher matcher = pattern.matcher(email);
       if(matcher.matches()){
          status = true;
         }
      else{
          status = false;
         }
         return status;
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegistrationIcon;
    private javax.swing.JLabel RegistrationImage;
    private javax.swing.JLabel RegistrationTitle;
    private javax.swing.JLabel avatar;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel cPasswordLabel;
    private javax.swing.JPasswordField cPasswordText;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel eAddressLabel;
    private javax.swing.JTextField eAddressText;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameText;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField lNameText;
    private javax.swing.JLabel loginLink;
    private javax.swing.JLabel nationalIdNumberLabel;
    private javax.swing.JTextField nationalIdNumberText;
    private javax.swing.JLabel pNumberLabel;
    private javax.swing.JTextField pNumberText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JTextField roleText;
    private javax.swing.JLabel staffIdNumberLabel;
    private javax.swing.JTextField staffIdNumberText;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel yobLabel;
    private javax.swing.JTextField yobText;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kwanza tukule icon.png")));
    }
}
