/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kwanza.tukule.management.system;

import javax.mail.Session;
import com.mysql.cj.protocol.Message;
import java.awt.HeadlessException;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.mail.Transport;
import javax.mail.internet.MimeMessage;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.swing.Icon;

/**
 *
 * @author Mariwa
 */
public class ForgotPassword extends javax.swing.JFrame {
     int randomCode;
     public Icon icon = new javax.swing.ImageIcon(getClass().getResource("kwanza tukule icon.png"));
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        verificationLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        verificationText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        verifyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kwanza Tukule | Forgot Password");
        getContentPane().setLayout(null);

        forgotLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        forgotLabel.setText("Forgot Password");
        getContentPane().add(forgotLabel);
        forgotLabel.setBounds(326, 75, 209, 64);

        emailLabel.setText("E-mail Address:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(122, 162, 101, 16);

        verificationLabel.setText("Verification code:");
        getContentPane().add(verificationLabel);
        verificationLabel.setBounds(122, 282, 110, 16);

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        getContentPane().add(emailText);
        emailText.setBounds(229, 157, 420, 26);

        verificationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificationTextActionPerformed(evt);
            }
        });
        getContentPane().add(verificationText);
        verificationText.setBounds(238, 277, 410, 26);

        submitButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(315, 213, 140, 40);

        verifyButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(verifyButton);
        verifyButton.setBounds(315, 344, 140, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/Kwanza Tukule.jpeg"))); // NOI18N

        logoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kwanza/tukule/management/system/kwanza tukule logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoPanel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificationTextActionPerformed
        if(Integer.valueOf(verificationText.getText())==randomCode)
        {
            ResetPassword rs = new ResetPassword(emailText.getText());
            rs.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "The codes do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_verificationTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        try{
        Random rand = new Random();
        randomCode = rand.nextInt(999999);
        String host = "smtp.gmail.com";
        String user = "samuelmariwa@gmail.com";
        //String user = "info@kwanzatukule.com";
        String pass = "samokoth.1999";
        //String pass = "Thamestana";
        String to = emailText.getText();
        String subject = "Verification Code";
        String message = "Your verification code is"+randomCode;
        boolean sessionDebug = false;
        Properties pros = System.getProperties();
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host","host");
        pros.put("mail.smtp.port", "587");
        pros.put("mail.smtp.auth", "true");
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.starttls.required","true");
        pros.put("mail.smtp.socketFactory.port", "465");  
        pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");  
        pros.put("mail.smtp.socketFactory.fallback", "false");  
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros,null);
        mailSession.setDebug(sessionDebug);
        MimeMessage msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(user));
        InternetAddress [] address = {new InternetAddress(to)};
        msg.setRecipients(RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
        Transport transport = mailSession.getTransport("smtp");
        transport.connect(host, user, pass);
        transport.sendMessage(msg, msg.getAllRecipients());
        transport.close();
        JOptionPane.showMessageDialog(this, "The verification code has been sent to your email.","Sent",JOptionPane.INFORMATION_MESSAGE,icon);
       }catch( Exception ex ){
           JOptionPane.showMessageDialog(rootPane,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
       }
    }//GEN-LAST:event_emailTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
       try{
        Random rand = new Random();
        randomCode = rand.nextInt(999999);
        String host = "smtp.gmail.com";
        String user = "samuelmariwa@gmail.com";
        //String user = "info@kwanzatukule.com";
        String pass = "samokoth.1999";
        //String pass = "Thamestana";
        String to = emailText.getText();
        String subject = "Verification Code";
        String message = "Your verification code is"+randomCode;
        boolean sessionDebug = false;
        Properties pros = System.getProperties();
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host","host");
        pros.put("mail.smtp.port", "587");
        pros.put("mail.smtp.auth", "true");
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.starttls.required","true");
        pros.put("mail.smtp.socketFactory.port", "465");  
        pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");  
        pros.put("mail.smtp.socketFactory.fallback", "false");  
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros,null);
        mailSession.setDebug(sessionDebug);
        MimeMessage msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(user));
        InternetAddress [] address = {new InternetAddress(to)};
        msg.setRecipients(RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
        Transport transport = mailSession.getTransport("smtp");
        transport.connect(host, user, pass);
        transport.sendMessage(msg, msg.getAllRecipients());
        transport.close();
        JOptionPane.showMessageDialog(this, "The verification code has been sent to your email.","Sent",JOptionPane.INFORMATION_MESSAGE,icon);
       }catch( Exception ex ){
           JOptionPane.showMessageDialog(rootPane,ex,"Oops!Something went wrong!",JOptionPane.INFORMATION_MESSAGE,icon);
       }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        if(Integer.valueOf(verificationText.getText())==randomCode)
        {
            ResetPassword rs = new ResetPassword(emailText.getText());
            rs.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "The codes do not match.","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_verifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel verificationLabel;
    private javax.swing.JTextField verificationText;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
